# Generated by Django 5.2.3 on 2025-07-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="author_name",
        ),
    ]
