# Generated by Django 5.2.4 on 2025-07-22 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_rename_name_category_author_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="BlogCategory",
        ),
        migrations.AlterField(
            model_name="blog",
            name="Published_Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
